version: '3.7'
services:
  # The core platform, mounts docker control socket and route definition into the image
  airport:
    image: ashokkumarta/ids-trusted-connector
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings-subscriber-2.mapdb:/root/etc/settings.mapdb
      - ../etc/airport.p12:/root/etc/airport.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./subscriber-2.xml:/root/deploy/subscriber-2.xml
    # Enable this port mappings for debugging or UI access from localhost
    ports:
      - "9982:8080"
    networks:
      - ids-local

  airport-demand-forecast-app:
    image: ashokkumarta/subscriber-2-demand-forecast
    networks:
      - ids-local
  airport-optimizer-feedback-app:
    image: ashokkumarta/subscriber-optimizer-feedback
    networks:
      - ids-local
  airport-allocation-confirmation-app:
    image: ashokkumarta/subscriber-allocation-confirmation
    networks:
      - ids-local

networks:
  ids-local:
    driver: bridge    
    
