version: '3.7'
services:
  # The core platform, mounts docker control socket and route definition into the image
  hospital:
    image: ashokkumarta/ids-trusted-connector
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings-subscriber-1.mapdb:/root/etc/settings.mapdb
      - ../etc/hospital.p12:/root/etc/hospital.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./subscriber-1.xml:/root/deploy/subscriber-1.xml
    # Enable this port mappings for debugging or UI access from localhost
    ports:
      - "9981:8080"
    networks:
      - ids-local

  hospital-demand-forecast-app:
    image: ashokkumarta/subscriber-1-demand-forecast
    networks:
      - ids-local
  hospital-optimizer-feedback-app:
    image: ashokkumarta/subscriber-optimizer-feedback
    networks:
      - ids-local
  hospital-allocation-confirmation-app:
    image: ashokkumarta/subscriber-allocation-confirmation
    networks:
      - ids-local

networks:
  ids-local:
    driver: bridge    
    
